### ISSUE TITLE
Support for Gradle 3.5

### ISSUE THREAD

**Issue by sdelamo** [energizedwork/webdriver-binaries-gradle-plugin#2]
Hello, 

Would it be possible for this plugin to support Gradle 3.5 or higher?. 

I would like to use with the latest version of Grails 3 which is currently recommend to use Gradle 3.5. 

thanks

**Comment by erdi** [comment]
The plugin only works with Gradle 4+, because I used [the new alternative to convention mapping in the form of `PropertyState`](https://docs.gradle.org/4.0/release-notes.html#public-type-for-representing-lazily-evaluated-properties).

I'm happy to revert back to using convention mapping and make the plugin Gradle 3.5+ compatible.

**Comment by erdi** [comment]
I will cut a release tomorrow and comment on this ticket when it's available.

**Comment by erdi** [comment]
With a bit of a delay but a [Gradle 3.5 compatible version of the plugin](https://plugins.gradle.org/plugin/com.energizedwork.webdriver-binaries/1.1) is now available, @sdelamo.
